### ISSUE TITLE
Create a Forge Basics wiki page, to explain the basics of Forge

### ISSUE THREAD

**Issue by TransRights** [weterandevelopment/wethack#5]

**Comment by Crystallinqq** [comment]
what the fuck is a java....

**Comment by Crystallinqq** [comment]
?

**Comment by AverageComet250** [comment]
Things such as the forge docs exist, and there are tutorials on YouTube for how to make Minecraft forge mods, which is basically everything you need to know, as well as some OOP and basic java knowledge, both acquirable through YouTube, c# or c++ experience, and you can always go on codecademy and use their java course.

Tl;Dr: this isn't necessary.
